INSERT INTO category (description, day_of_debit) VALUES ('CZ ziektekostenverzekering', 4);
INSERT INTO category (description, day_of_debit) VALUES ('BBC voetbal contributie', 24);
INSERT INTO category (description, day_of_debit) VALUES ('Simyo telefoonabonnement', 26);
INSERT INTO category (description, day_of_debit) VALUES ('Wegenbelasting Volvo V40', 27);
INSERT INTO category (description, day_of_debit) VALUES ('Wegenbelasting Volkswagen UP', 27);
INSERT INTO category (description, day_of_debit) VALUES ('Waterschapslasten', 29);
INSERT INTO category (description, day_of_debit) VALUES ('Onroerendzaakbelasting', 30);
INSERT INTO category (description, day_of_debit) VALUES ('Waldsang muziekschool contributie', 30);
INSERT INTO category (description, day_of_debit) VALUES ('Twente uitvaartverzekering', 30);
INSERT INTO category (description, day_of_debit) VALUES ('Diesel Volvo V40', 1);
INSERT INTO category (description, day_of_debit) VALUES ('Aflossing hypotheek', 1);
INSERT INTO category (description, day_of_debit) VALUES ('Hypotheek rente', 1);
INSERT INTO category (description, day_of_debit) VALUES ('Energiekosten', 2);
INSERT INTO category (description, day_of_debit) VALUES ('Interpolis overlijdensrisicoverzekering', 6);
INSERT INTO category (description, day_of_debit) VALUES ('Interpolis Alles-in-1-polis', 6);
INSERT INTO category (description, day_of_debit) VALUES ('Vitens waterlasten', 7);
INSERT INTO category (description, day_of_debit) VALUES ('Ziektekosten', 4);
INSERT INTO category (description, day_of_debit) VALUES ('Spotify', 20);
INSERT INTO category (description, day_of_debit) VALUES ('Netflix', 20);
INSERT INTO category (description, day_of_debit) VALUES ('Ziggo Internet+TV', 14);